<?php
/**
 * CurrentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Weather API
 *
 * # Introduction  WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy.    We provide following data through our API:     - Real-time weather - 14 day weather forecast - Astronomy - Time zone - Location data - Search or Autocomplete API - NEW: Historical weather - NEW: Future Weather (Upto 300 days ahead) - Weather Alerts - Air Quality Data  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!    We have [code libraries](https://www.weatherapi.com/docs/code-libraries.aspx) for different programming languages like PHP, .net, JAVA, etc.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.  Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=<YOUR API KEY>
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CurrentTest Class Doc Comment
 *
 * @category    Class
 * @description Current
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Current"
     */
    public function testCurrent()
    {
    }

    /**
     * Test attribute "last_updated_epoch"
     */
    public function testPropertyLastUpdatedEpoch()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "temp_c"
     */
    public function testPropertyTempC()
    {
    }

    /**
     * Test attribute "temp_f"
     */
    public function testPropertyTempF()
    {
    }

    /**
     * Test attribute "is_day"
     */
    public function testPropertyIsDay()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "wind_mph"
     */
    public function testPropertyWindMph()
    {
    }

    /**
     * Test attribute "wind_kph"
     */
    public function testPropertyWindKph()
    {
    }

    /**
     * Test attribute "wind_degree"
     */
    public function testPropertyWindDegree()
    {
    }

    /**
     * Test attribute "wind_dir"
     */
    public function testPropertyWindDir()
    {
    }

    /**
     * Test attribute "pressure_mb"
     */
    public function testPropertyPressureMb()
    {
    }

    /**
     * Test attribute "pressure_in"
     */
    public function testPropertyPressureIn()
    {
    }

    /**
     * Test attribute "precip_mm"
     */
    public function testPropertyPrecipMm()
    {
    }

    /**
     * Test attribute "precip_in"
     */
    public function testPropertyPrecipIn()
    {
    }

    /**
     * Test attribute "humidity"
     */
    public function testPropertyHumidity()
    {
    }

    /**
     * Test attribute "cloud"
     */
    public function testPropertyCloud()
    {
    }

    /**
     * Test attribute "feelslike_c"
     */
    public function testPropertyFeelslikeC()
    {
    }

    /**
     * Test attribute "feelslike_f"
     */
    public function testPropertyFeelslikeF()
    {
    }

    /**
     * Test attribute "vis_km"
     */
    public function testPropertyVisKm()
    {
    }

    /**
     * Test attribute "vis_miles"
     */
    public function testPropertyVisMiles()
    {
    }

    /**
     * Test attribute "uv"
     */
    public function testPropertyUv()
    {
    }

    /**
     * Test attribute "gust_mph"
     */
    public function testPropertyGustMph()
    {
    }

    /**
     * Test attribute "gust_kph"
     */
    public function testPropertyGustKph()
    {
    }

    /**
     * Test attribute "air_quality"
     */
    public function testPropertyAirQuality()
    {
    }
}
