<?php
/**
 * ForecastDayTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Weather API
 *
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.36
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ForecastDayTest Class Doc Comment
 *
 * @category    Class
 * @description ForecastDay
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ForecastDayTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ForecastDay"
     */
    public function testForecastDay()
    {
    }

    /**
     * Test attribute "maxtemp_c"
     */
    public function testPropertyMaxtempC()
    {
    }

    /**
     * Test attribute "maxtemp_f"
     */
    public function testPropertyMaxtempF()
    {
    }

    /**
     * Test attribute "mintemp_c"
     */
    public function testPropertyMintempC()
    {
    }

    /**
     * Test attribute "mintemp_f"
     */
    public function testPropertyMintempF()
    {
    }

    /**
     * Test attribute "avgtemp_c"
     */
    public function testPropertyAvgtempC()
    {
    }

    /**
     * Test attribute "avgtemp_f"
     */
    public function testPropertyAvgtempF()
    {
    }

    /**
     * Test attribute "maxwind_mph"
     */
    public function testPropertyMaxwindMph()
    {
    }

    /**
     * Test attribute "maxwind_kph"
     */
    public function testPropertyMaxwindKph()
    {
    }

    /**
     * Test attribute "totalprecip_mm"
     */
    public function testPropertyTotalprecipMm()
    {
    }

    /**
     * Test attribute "totalprecip_in"
     */
    public function testPropertyTotalprecipIn()
    {
    }

    /**
     * Test attribute "avgvis_km"
     */
    public function testPropertyAvgvisKm()
    {
    }

    /**
     * Test attribute "avgvis_miles"
     */
    public function testPropertyAvgvisMiles()
    {
    }

    /**
     * Test attribute "avghumidity"
     */
    public function testPropertyAvghumidity()
    {
    }

    /**
     * Test attribute "daily_will_it_rain"
     */
    public function testPropertyDailyWillItRain()
    {
    }

    /**
     * Test attribute "daily_chance_of_rain"
     */
    public function testPropertyDailyChanceOfRain()
    {
    }

    /**
     * Test attribute "daily_will_it_snow"
     */
    public function testPropertyDailyWillItSnow()
    {
    }

    /**
     * Test attribute "daily_chance_of_snow"
     */
    public function testPropertyDailyChanceOfSnow()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "uv"
     */
    public function testPropertyUv()
    {
    }
}
