<?php
/**
 * MarineHourTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Weather API
 *
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.36
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MarineHourTest Class Doc Comment
 *
 * @category    Class
 * @description MarineHour
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarineHourTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MarineHour"
     */
    public function testMarineHour()
    {
    }

    /**
     * Test attribute "time_epoch"
     */
    public function testPropertyTimeEpoch()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "temp_c"
     */
    public function testPropertyTempC()
    {
    }

    /**
     * Test attribute "temp_f"
     */
    public function testPropertyTempF()
    {
    }

    /**
     * Test attribute "is_day"
     */
    public function testPropertyIsDay()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "wind_mph"
     */
    public function testPropertyWindMph()
    {
    }

    /**
     * Test attribute "wind_kph"
     */
    public function testPropertyWindKph()
    {
    }

    /**
     * Test attribute "wind_degree"
     */
    public function testPropertyWindDegree()
    {
    }

    /**
     * Test attribute "wind_dir"
     */
    public function testPropertyWindDir()
    {
    }

    /**
     * Test attribute "pressure_mb"
     */
    public function testPropertyPressureMb()
    {
    }

    /**
     * Test attribute "pressure_in"
     */
    public function testPropertyPressureIn()
    {
    }

    /**
     * Test attribute "precip_mm"
     */
    public function testPropertyPrecipMm()
    {
    }

    /**
     * Test attribute "precip_in"
     */
    public function testPropertyPrecipIn()
    {
    }

    /**
     * Test attribute "humidity"
     */
    public function testPropertyHumidity()
    {
    }

    /**
     * Test attribute "cloud"
     */
    public function testPropertyCloud()
    {
    }

    /**
     * Test attribute "feelslike_c"
     */
    public function testPropertyFeelslikeC()
    {
    }

    /**
     * Test attribute "feelslike_f"
     */
    public function testPropertyFeelslikeF()
    {
    }

    /**
     * Test attribute "windchill_c"
     */
    public function testPropertyWindchillC()
    {
    }

    /**
     * Test attribute "windchill_f"
     */
    public function testPropertyWindchillF()
    {
    }

    /**
     * Test attribute "heatindex_c"
     */
    public function testPropertyHeatindexC()
    {
    }

    /**
     * Test attribute "heatindex_f"
     */
    public function testPropertyHeatindexF()
    {
    }

    /**
     * Test attribute "dewpoint_c"
     */
    public function testPropertyDewpointC()
    {
    }

    /**
     * Test attribute "dewpoint_f"
     */
    public function testPropertyDewpointF()
    {
    }

    /**
     * Test attribute "will_it_rain"
     */
    public function testPropertyWillItRain()
    {
    }

    /**
     * Test attribute "chance_of_rain"
     */
    public function testPropertyChanceOfRain()
    {
    }

    /**
     * Test attribute "will_it_snow"
     */
    public function testPropertyWillItSnow()
    {
    }

    /**
     * Test attribute "chance_of_snow"
     */
    public function testPropertyChanceOfSnow()
    {
    }

    /**
     * Test attribute "vis_km"
     */
    public function testPropertyVisKm()
    {
    }

    /**
     * Test attribute "vis_miles"
     */
    public function testPropertyVisMiles()
    {
    }

    /**
     * Test attribute "gust_mph"
     */
    public function testPropertyGustMph()
    {
    }

    /**
     * Test attribute "gust_kph"
     */
    public function testPropertyGustKph()
    {
    }

    /**
     * Test attribute "sig_ht_mt"
     */
    public function testPropertySigHtMt()
    {
    }

    /**
     * Test attribute "swell_ht_mt"
     */
    public function testPropertySwellHtMt()
    {
    }

    /**
     * Test attribute "swell_ht_ft"
     */
    public function testPropertySwellHtFt()
    {
    }

    /**
     * Test attribute "swell_dir"
     */
    public function testPropertySwellDir()
    {
    }

    /**
     * Test attribute "swell_dir_16_point"
     */
    public function testPropertySwellDir16Point()
    {
    }

    /**
     * Test attribute "swell_period_secs"
     */
    public function testPropertySwellPeriodSecs()
    {
    }

    /**
     * Test attribute "uv"
     */
    public function testPropertyUv()
    {
    }
}
